name: Build App macOs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # --- DOWNLOAD FFMPEG OTOMATIS (AGAR ANDA TIDAK PERLU UPLOAD 70MB) ---
    - name: Download & Setup FFmpeg Mac (Auto)
      run: |
        mkdir -p bin/mac
        curl -L -o ffmpeg_mac.zip "https://evermeet.cx/ffmpeg/getrelease/zip"
        unzip -o ffmpeg_mac.zip
        mv ffmpeg bin/mac/
        chmod +x bin/mac/ffmpeg
        ls -l bin/mac/

    - name: Build Application with PyInstaller
      run: |
        # PERHATIKAN BARIS ICON DI BAWAH INI
        # Pastikan nama file "app_icon.icns" SESUAI dengan nama file icon yang Anda upload di GitHub
        
        pyinstaller --noconfirm --clean --windowed \
          --name "IntisariClips" \
          --icon "app_icon.icns" \
          --add-binary "bin/mac/ffmpeg:bin/mac" \
          --collect-all customtkinter \
          AutoClipintisari.py

    - name: Create ZIP Bundle
      run: |
        cd dist
        ditto -c -k --keepParent "IntisariClips.app" "IntisariClips-MacOS.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IntisariClips-MacOS
        path: dist/IntisariClips-MacOS.zip
